### ISSUE TITLE
/usr/local/bin/gravityOptimise.sh: fork: Cannot allocate memory

### ISSUE THREAD

**Issue by ssneoh** [mmotti/pihole-gravity-optimise#1]
When I run 'gravityOptimise.sh' got error as tittle.

root@raspberrypi:/usr/local/bin# gravityOptimise.sh
# Gravity
[i] Updating gravity.list
[i] 1748482 gravity list entries
# Wildcards
[i] Fetching wildcards from /etc/dnsmasq.d
[i] 31353 wildcards found
[i] Reading /etc/pihole/gravity.list
[i] Removing wildcard matches
/usr/local/bin/gravityOptimise.sh: fork: Cannot allocate memory
[i] No changes required.
# Regexps
[i] 16 regexps found
[i] Identifying unnecessary domains
/usr/local/bin/gravityOptimise.sh: fork: Cannot allocate memory

Please advise. Thanks.

**Comment by mmotti** [comment]
Hi,

I have not come across that error before - Is it possible that you have run out of allocated memory?

Also - I have, within the last few minutes, updated the script. Perhaps give the new one a quick try?

**Comment by ssneoh** [comment]
The issue with error gone after updating the script.
Thanks :)
