### ISSUE TITLE
install pyahocorasick fails

### ISSUE THREAD

**Issue by Gizmo-Ger** [mmotti/pihole-gravity-optimise#10]
the transition to python caused a little glitch on my end.

root@rock64:~# sudo pip3 install pyahocorasick
Collecting pyahocorasick
  Using cached https://files.pythonhosted.org/packages/f4/9f/f0d8e8850e12829eea2e778f1c90e3c53a9a799b7f412082a5d21cd19ae1/pyahocorasick-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-90_hp29t/pyahocorasick/

**Comment by mmotti** [comment]
Thanks for your feedback! This is helpful to know what packages are
required.

Can you please run:  

sudo pip3 install setuptools

and try again to install pyahocorasick?

Cheers!

**Comment by mmotti** [comment]
Edit:

After further experimenting with DietPi (cut-down OS), it looks like the following are required:

**Packages**
`sudo apt-get install python3 python3-pip python3-dev build-essential`

**Modules**
`sudo pip3 install setuptools wheel`
`sudo pip3 install pyahocorasick`

I took a clean install of DietPi and those are the barebones required to get some of the Python modules to install properly :-) I've updated the documentation again to reflect this. These packages are pre-installed on a lot of distributions but not DietPi.

I hope this helps! Let me know.

**Comment by Gizmo-Ger** [comment]
Works so far with the modules but getting following error while running the script.

Traceback (most recent call last):
  File "<stdin>", line 78, in <module>
  File "<stdin>", line 78, in <genexpr>
  File "<stdin>", line 78, in <genexpr>
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 1658: invalid continuation byte

I´m running Linux rock64 4.4.190-1233-rockchip-ayufan-gd3f1be0ed310

**Comment by mmotti** [comment]
Ah, I imagine this could be caused by non-utf8 characters.

Please could you confirm your blocklists so I can replicate it on my end? 😊

**Comment by mmotti** [comment]
I have updated the script to exclude non UTF-8 characters which could be introduced due to the fact that there are so many list maintainers that inevitably end up contributing to gravity.list

Please could you try running again, and make sure that you see: 
`[i] Updating gravity (this may take a little time)`

Specifically, the note that the gravity update may take a little time. This is another small change I made and it will indicate that you are using the latest version of the script and not a cached version (depending on how you're downloading / running it)

I found a huge list of blocklists are ran the script, and this is my output:
```
mmotti@ubuntu-server:~$ curl -sSl https://raw.githubusercontent.com/mmotti/pihole-gravity-optimise/master/gravityOptimise.py | sudo python3
[i] Root user detected
[i] Pi-hole path exists
[i] Updating gravity (this may take a little time)
[i] Legacy regex.list detected
[i] Fetching domains
[i] --> 983153 domains found
[i] Scanning /etc/dnsmasq.d for wildcards
[i] --> 35877 wildcards found
[i] Identifying wildcard conflicts with gravity
[i] --> 174659 conflicts found
[i] Fetching regexps
[i] --> 16 regexps found
[i] Checking for gravity matches
[i] --> 29834 matches found in gravity
[i] Outputting updated gravity.list
[i] --> 762344 domains remain in gravity.list
[i] Restarting Pi-hole
```

**Comment by Gizmo-Ger** [comment]
curl -sSl https://raw.githubusercontent.com/mmotti/pihole-gravity                       -optimise/master/gravityOptimise.py | sudo python3
[i] Root user detected
[i] Pi-hole path exists
[i] Updating gravity (this may take a little time)
[i] Legacy lists detected
[i] Fetching domains
[i] --> 785879 domains found
[i] Scanning /etc/dnsmasq.d for wildcards
[i] --> No wildcards found
[i] Fetching regexps
Traceback (most recent call last):
  File "<stdin>", line 160, in <module>
  File "<stdin>", line 160, in <genexpr>
  File "<stdin>", line 160, in <genexpr>
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 2670: invalid start byte

**Comment by mmotti** [comment]
Hmm.. I would expect non utf-8 characters in gravity but regex is more of a
surprise.

Please could you post the output of:

cat /etc/pihole/regex.list

It's easy enough to apply the same filter to regex.list but I'd ideally
like to see what's causing it

>

**Comment by Gizmo-Ger** [comment]
I´m sorry for the late reply due to the holidays.

regex.list
(googlesyndication\.com)$
(1stok\.com)$
(strip\.alicdn\.com)$
(247realmedia\.com)$
(2cnt\.net)$
(2mdn\.net)$
(2o7\.net)$
(302br\.net)$
(51yes\.com)$
(about-tabs\.com)$
(adalyser\.com)$
(adbrite\.com)$
(adbureau\.net)$
(addthis\.com)$
(adk2\.co)$
(admob\.com)$
(adnxs\.com)$
(adocean\.pl)$
(adprotect\.net)$
(adsafeprotected\.com)$
(adscience\.nl)$
(adserver\.com)$
(adtech\.de)$
(adtech\.fr)$
(adtech\.us)$
(adtlgc\.com)$
(advance\.net)$
(advertising\.com)$
(advertserve\.com)$
(am15\.net)$
(amazon-adsystem\.com)$
(appier\.net)$
(applovin\.com)$
(atdmt\.com)$
(bannerbank\.ru)$
(bbelements\.com)$
(bravenet\.com)$
(casalemedia\.com)$
(cedexis-radar\.net)$
(checkm8\.com)$
(cjt1\.net)$
(cnzz\.com)$
(cqcounter\.com)$
(crashlytics\.com)$
(crypto-loot\.com)$
(doubleclick\.be)$
(doubleclick\.net)$
(dynamic\.dol\.ru)$
(economicoutlook\.net)$
(esomniture\.com)$
(estat\.com)$
(extreme-dm\.com)$
(ezcybersearch\.com)$
(falkag\.net)$
(fastclick\.net)$
(focalink\.com)$
(gemius\.pl)$
(geovisite\.com)$
(glam\.com)$
(glpals\.com)$
(googleadservices\.com)$
(google-analytics\.com)$
(googlezip\.net)$
(groovinads\.com)$
(hitbox\.com)$
(hotlog\.ru)$
(hpg\.com\.br)$
(hpg\.ig\.com\.br)$
(hut1\.ru)$
(hyperbanner\.net)$

(intellitxt\.com)$
(iovation\.com)$
(kaffnet\.com)$
(kontera\.com)$
(linkpulse\.com)$
(liteweb\.net)$
(liveadvert\.com)$
(marketgid\.com)$
(marketscore\.com)$
(mydas\.mobi)$
(oewabox\.at)$
(omniture\.com)$
(omtrdc\.net)$
(opentracker\.net)$
(ourtablets\.com)$
(p2l\.info)$
(paycount\.com)$
(petrovka\.info)$
(polybuild\.ru)$
(pop6\.com)$
(popmarker\.com)$
(popupad\.net)$
(pos\.baidu\.com)$
(sapo\.pt)$
(servedbyopenx\.com)$
(sextracker\.be)$
(sextracker\.com)$
(sextracker\.de)$
(shengen\.ru)$
(sitemeter\.com)$
(smartadserver\.com)$
(spylog\.com)$
(startappexchange\.com)$
(startappnetwork\.com)$
(startappservice\.com)$
(statcounter\.com)$
(surf-town\.net)$
(thruport\.com)$
(tradedoubler\.com)$
(tsyndicate\.com)$
(tynt\.com)$
(vkuservideo\.net)$
(voluumtrk\.com)$
(voodoo\.com)$
(web3000\.com)$
(webtrekk\.net)$
(xiti\.com)$
(xxxcounter\.com)$
(youku\.com)$
(zedo\.com)$
^(ad\.)
^(ad1\.)
^(ad2\.)
^(ad3\.)
^(adimages\.)
^(ads\.)
^(ads1\.)
^(ads2\.)
^(ads3\.)
^(ads4\.)
^(ads5\.)
^(adserv\.)
^(adserve\.)
^(adserver\.)
^(adserver1\.)
^(adserver2\.)
^(adsrv\.)
^(adv\.)
^(advertising\.)
^(adx\.)
^(aff\.)
^(affiliate\.)
^(affiliates\.)
^(analytics\.)
^(banner\.)
^(banners\.)
^(click\.)
^(clicks\.)
^(counter\.)
^(gcirm\.)
^(oas\.)
^(oascentral\.)
^(phorm\.)
^(pixel\.)
^(protection\.)
^(reklam\.)
^(scrooge\.)
^(stat\.)
^(stats\.)
^(track\.)
^(tracker\.)
^(tracking\.)
^(.+[-_.])??adse?rv(er?|ice)?s?[0-9]*[-.]
^(.+[-.])??m?ad[sxv]?[0-9]*[-.]
^(.+[-_.])??xn–
^adim(age|g)s?[0-9]*[-_.]
^adtrack(er|ing)?[0-9]*[-.]
^advert(s|is(ing|ements?))?[0-9]*[-_.]
^aff(iliat(es?|ion))?[-.]
^analytics?[-.]
^banners?[-.]
^count(ers?)?[0-9]*[-.]
^pixels?[-.]
^stat(s|istics)?[0-9]*[-.]
^telemetry[-.]
^track(ers?|ing)?[0-9]*[-.]
^traff(ic)?[-.]

**Comment by mmotti** [comment]
No problem :) if you try the latest version of the script it should
hopefully work for you.

**Comment by Gizmo-Ger** [comment]
Thanks mate for the Xmas present - it works like a charme. ;-)

**Comment by mmotti** [comment]
Haha you're welcome!
