### ISSUE TITLE
Domain discrepancy on pi-hole dashboard

### ISSUE THREAD

**Issue by cleanev** [mmotti/pihole-gravity-optimise#15]
Hello,
After full update and running pihole-optimize dashboard still shows original number that was downloaded to gravity. I posted this in pi-hole and one of the developer asked me to reach out to script owner.
Here’s a link to the posting
https://discourse.pi-hole.net/t/discrepancy-among-displayed-domains-vs-real-domains/28491/4
Thanks

**Comment by mmotti** [comment]
Thanks for reporting :-) I will take a look.

This could be new behaviour by the gravity process. If so, it's not a
problem; I just need to update an extra field in the database

**Comment by mmotti** [comment]
I have updated the script to update **gravity_count** in the **info** table. I had missed that they'd made some changes to the DB earlier this month.

Should work now. See https://github.com/mmotti/pihole-gravity-optimise/commit/52898b99912dde70b97e27743f0debe4572e5ff9
