### ISSUE TITLE
File: command not found

### ISSUE THREAD

**Issue by curiosity-seeker** [mmotti/pihole-gravity-optimise#3]
@mmotti : First of all, thank you very much for your excellent work! I'm using your scripts successfully with Pi-hole - much appreciated!

One question, though:
When running gravityOptimise.sh I'm getting the error:
`/usr/local/bin/gravityOptimise.sh: line 78: file: command not found`
which points to `iconv`. A similar error message appears when running generateGravityWildcards.sh (line 163). 

The funny thing is that iconv is installed on my RaspberryPI:
```
root@DietPi:~# which -a iconv
/usr/bin/iconv
```
So I don't understand why this error occurs. Any ideas?

I'm not sure what iconv is suggested to do. That the scripts don't find it doesn't seem to have any negative consequences.

**Comment by mmotti** [comment]
Hi :-)

It would appear to be an issue with the `file` command as opposed to `iconv`.

iconv is basically used to convert the encoding of the gravity file to UTF-8 as some blocklists have been found to include non UTF-8 characters.

The `file` command is used in this instance to get the current encoding of the temporary gravity file, to feed to the input of iconv so it knows that it needs to convert from X to UTF-8

I just downloaded the DietPi VM image and it would appear that the `file` command is not installed by default for whatever reason.

You could likely fix this issue with:
`sudo apt-get update`
`sudo apt-get install file`

**Comment by curiosity-seeker** [comment]
You are absolutely right - it was `file` that was missing! I was obviously blind. Embarrassing ...

Thanks again for your great work!
