### ISSUE TITLE
Getting an allocate issue

### ISSUE THREAD

**Issue by GokulG07** [mmotti/pihole-gravity-optimise#4]
pi@raspberrypi:~ $ gravityOptimise.sh
[i] Updating gravity
/usr/local/bin/gravityOptimise.sh: xrealloc: cannot allocate 257118336 bytes

**Comment by DannyBeanz** [comment]
Same here.  I get a slight variation:

pi@raspberrypi:~ $ gravityOptimise.sh
[i] Updating gravity
/usr/local/bin/gravityOptimise.sh: fork: Cannot allocate memory

If I comment out the 'pihole -g' command around line 61, I get a little further but ultimatley the same issue I believe:

pi@raspberrypi:~ $ gravityOptimise.sh
[i] Updating gravity
[i] Parsing existing wildcard config (DNSMASQ)
[i] Removing wildcard matches from gravity
/usr/local/bin/gravityOptimise.sh: fork: Cannot allocate memory

**Comment by mmotti** [comment]
Hmm this is an odd one. What device are you running the scripts on? Do you have a significant number of domains in your blocklists (I.e. Millions)?

**Comment by DannyBeanz** [comment]
This occurs on a Raspberry Pi 3b+ with 1.95m domains on the blocklist.

It also occurs on a Google Cloud f1-micro (1 vCPU, 0.6 GB memory) 900k domains on the blocklist

**Comment by CVJoint** [comment]
I was getting something similar on the 3b+ running in docker

**Comment by GokulG07** [comment]
I'm using rpi 2... I think it may be limitation of my sdcard (run out of memory i think)

**Comment by DannyBeanz** [comment]
I'm not convinced of the sdcard point, mine has a ton of space.

**Comment by GokulG07** [comment]
Yea me too...will swap the sdcard and will update and see...as mine is out of memory.. Who knows!

**Comment by mmotti** [comment]
Have you guys checked your available memory (RAM)? I'm not a linux wizard but my google-fu seems to suggest it's memory / RAM related and I can imagine that you would be more susceptible to this with large blocklists.

**Comment by GokulG07** [comment]
Yes, mine at 39% usage now... Haven't see exceeding 45% till now.

**Comment by DannyBeanz** [comment]
Using `free -m`, I can see I have 926Mb total with 626Mb available.

The PiHole admin interface tells me I have 26.3% used.


HTH

**Comment by mmotti** [comment]
I've just re-wrote the scripts in Python. If you get a chance, can you give it a try to see if it resolves the issue?

**Comment by DannyBeanz** [comment]
Will likely be in a position to try this out in the next day or so, before the holidays.

**Comment by mmotti** [comment]
No rush :)

There are some additional requirements for running the Python version; I've
updated the instructions which I'm hoping will cover everyone and not just
my install.

Basically need Python 3 (usually pre-installed), a python module (for
matching search speed of grep) and the prerequisites for said Python module
- These have been confirmed for DietPi which is a minimal OS, so I still
need to check whether then python3-dev is definitely required for Raspbian.

Otherwise, the process is fairly similar. If there are still issues I may
need to separate out the calls to update gravity etc but let's see what
happens.

Also - You need to run the script as root (sudo). It was easier in Shell to
prefix only the necessary commands but I don't think this is as easy in
Python. Root is currently required for making modifications inside
`/etc/pihole` etc

**Comment by GokulG07** [comment]
Thank You #mmotti For your wonderful work.

Device Rpi2(Raspbian Buster Lite)
The 1st issue I had was with the python installation about the path not found 404 error, solved that by updating the OS system[apt-get update && upgrade](Its recommended before installing python).

another one is codec can't decode ....need help on this...

[i] Root user detected
[i] Pi-hole path exists
[i] Updating gravity
[i] Legacy regex.list detected
[i] Fetching domains
Traceback (most recent call last):
  File "<stdin>", line 78, in <module>
  File "<stdin>", line 78, in <genexpr>
  File "<stdin>", line 78, in <genexpr>
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 4514: invalid continuation byte

**Comment by mmotti** [comment]
Ah! That's a good point. I'll need to look into that... I've only ever used the `apt-get update` in the past but then I've always had Python pre-installed :) I'll try to remember to add to the instructions when I'm next on my laptop. 

I believe I may have resolved the decoding issue in the latest update - Can you try run the latest version? I can't be absolutely sure as none of the blocklists I can find include any non utf-8 characters which would cause this issue, but I'm fairly confident it should be fixed (excludes any characters that cause errors). 

Please see my last comment in here: https://github.com/mmotti/pihole-gravity-optimise/issues/10

**Comment by GokulG07** [comment]
I just did run the latest version now it ends up like this...

[i] Root user detected
[i] Pi-hole path exists
[i] Updating gravity (this may take a little time)
[i] Legacy regex.list detected
[i] Fetching domains
[i] --> 4365935 domains found
[i] Scanning /etc/dnsmasq.d for wildcards
[i] --> 35535 wildcards found
[i] Identifying wildcard conflicts with gravity
Killed
--------------

Trying again, now it is stuck on [i] Identifying wildcard conflicts with gravity, 
for over 20 min, still waiting will terminate and try again... will update you...

**Comment by mmotti** [comment]
Hmm that is a little concerning.

Are you able to share which host files you are using? 

I have only tested the performance of this properly on a VM with dietpi and ubuntu server. I will also try test in now with my RPI 3b. If it's painfully slow then I may need to go with a more crude method of identifying wildcard matches.

Edit:

This is the outcome from running on my Raspberry Pi 3b:
```
pi@raspberrypi:~$ time curl -sSl https://raw.githubusercontent.com/mmotti/pihole-gravity-optimise/master/gravityOptimise.py | sudo python3
[i] Root user detected
[i] Pi-hole path exists
[i] Updating gravity (this may take a little time)
[i] Legacy lists detected
[i] Fetching domains
[i] --> 1003241 domains found
[i] Scanning /etc/dnsmasq.d for wildcards
[i] --> 35876 wildcards found
[i] Identifying wildcard conflicts with gravity
[i] --> 138694 conflicts found
[i] Fetching regexps
[i] --> 16 regexps found
[i] Checking for gravity matches
[i] --> 44452 matches found in gravity
[i] Outputting updated gravity.list
[i] --> 788045 domains remain in gravity.list
[i] Restarting Pi-hole

real    1m46.788s
user    1m20.725s
sys     0m4.514s
```

The part that took the longest for me was the regexp matching, which I may need to look at how I can speed up (if at all). With 1,000,000 domains, it took ~8 seconds to process the wildcards matches for me and ~33 seconds to process the regexps.

**Comment by GokulG07** [comment]
NO luck as of now. Identifying wildcard conflicts with gravity is getting Killed after 30+min, Tried multiple times, not the latest version(Define regexps chunk size in variable) will try later as my ISP is down now. Attaching all the host I'm using 125 of them hope it helps.

  | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts |  
  | https://mirror1.malwaredomains.com/files/justdomains |  
  | http://sysctl.org/cameleon/hosts |  
  | https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt |  
  | https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt |  
  | https://hosts-file.net/ad_servers.txt |  
  | https://hosts-file.net/grm.txt |  
  | https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts |  
  | https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts |  
  | https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts |  
  | https://v.firebog.net/hosts/static/w3kbl.txt |  
  | https://v.firebog.net/hosts/BillStearns.txt |  
  | https://www.dshield.org/feeds/suspiciousdomains_Low.txt |  
  | https://www.dshield.org/feeds/suspiciousdomains_Medium.txt |  
  | https://www.dshield.org/feeds/suspiciousdomains_High.txt |  
  | https://www.joewein.net/dl/bl/dom-bl-base.txt |  
  | https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt |  
  | https://hostsfile.org/Downloads/hosts.txt |  
  | https://someonewhocares.org/hosts/zero/hosts |  
  | https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt |  
  | https://raw.githubusercontent.com/vokins/yhosts/master/hosts |  
  | http://winhelp2002.mvps.org/hosts.txt |  
  | https://hostsfile.mine.nu/hosts0.txt |  
  | https://v.firebog.net/hosts/Kowabit.txt |  
  | https://adblock.mahakala.is |  
  | https://adaway.org/hosts.txt |  
  | https://v.firebog.net/hosts/AdguardDNS.txt |  
  | https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt |  
  | https://v.firebog.net/hosts/Easylist.txt |  
  | https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts;showintro=0 |  
  | https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts |  
  | https://www.squidblacklist.org/downloads/dg-ads.acl |  
  | https://v.firebog.net/hosts/Easyprivacy.txt |  
  | https://v.firebog.net/hosts/Prigent-Ads.txt |  
  | https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt |  
  | https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts |  
  | https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt |  
  | https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt |  
  | https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt |  
  | https://v.firebog.net/hosts/Airelle-trc.txt |  
  | https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt |  
  | https://hosts-file.net/exp.txt |  
  | https://hosts-file.net/emd.txt |  
  | https://hosts-file.net/psh.txt |  
  | https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt |  
  | https://www.malwaredomainlist.com/hostslist/hosts.txt |  
  | https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt |  
  | https://v.firebog.net/hosts/Prigent-Malware.txt |  
  | https://v.firebog.net/hosts/Prigent-Phishing.txt |  
  | https://phishing.army/download/phishing_army_blocklist_extended.txt |  
  | https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt |  
  | https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt |  
  | https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt |  
  | https://ransomwaretracker.abuse.ch/downloads/LY_C2_DOMBL.txt |  
  | https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt |  
  | https://ransomwaretracker.abuse.ch/downloads/TL_C2_DOMBL.txt |  
  | https://v.firebog.net/hosts/Shalla-mal.txt |  
  | https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts |  
  | https://www.squidblacklist.org/downloads/dg-malicious.acl |  
  | https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt |  
  | https://v.firebog.net/hosts/Airelle-hrsk.txt |  
  | https://github.com/chadmayfield/pihole-blocklists/raw/master/lists/pi_blocklist_porn_all.list |  
  | https://zerodot1.gitlab.io/CoinBlockerLists/hosts |  
  | https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/adaway.org/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/adblock-nocoin-list/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/adguard-simplified/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/anudeepnd-adservers/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/disconnect.me-malvertising/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/disconnect.me-malware/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/disconnect.me-tracking/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/easylist/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/easyprivacy/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/eth-phishing-detect/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/fademind-add.2o7net/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/fademind-add.dead/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/fademind-add.risk/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/fademind-add.spam/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/kadhosts/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/malwaredomainlist.com/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/malwaredomains.com-immortaldomains/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/malwaredomains.com-justdomains/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/matomo.org-spammers/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/mitchellkrogza-badd-boyz-hosts/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/pgl.yoyo.org/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/ransomwaretracker.abuse.ch/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/someonewhocares.org/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/spam404.com/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/stevenblack/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/winhelp2002.mvps.org/list.txt |  
  | https://raw.githubusercontent.com/hectorm/hmirror/master/data/zerodot1-coinblockerlists-browser/list.txt |  
  | https://raw.githubusercontent.com/CHEF-KOCH/Audio-fingerprint-pages/master/AudioFp.txt |  
  | https://raw.githubusercontent.com/CHEF-KOCH/Canvas-fingerprinting-pages/master/Canvas.txt |  
  | https://raw.githubusercontent.com/CHEF-KOCH/WebRTC-tracking/master/WebRTC.txt |  
  | https://www.stopforumspam.com/downloads/toxic_domains_whole.txt |  
  | https://tspprs.com/dl/crypto |  
  | https://tspprs.com/dl/tracking |  
  | https://tspprs.com/dl/spotify |  
  | https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/AakList.txt |  
  | https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/Prebake-Obtrusive.txt |  
  | https://jasonhill.co.uk/pfsense/ytadblock.txt |  
  | https://raw.githubusercontent.com/CHEF-KOCH/BarbBlock-filter-list/master/HOSTS.txt |  
  | https://raw.githubusercontent.com/CHEF-KOCH/Canvas-Font-Fingerprinting-pages/master/Canvas.txt |  
  | http://phishing.mailscanner.info/phishing.bad.sites.conf |  
  | https://zerodot1.gitlab.io/CoinBlockerLists/list.txt |  
  | https://zerodot1.gitlab.io/CoinBlockerLists/list_browser.txt |  
  | https://zerodot1.gitlab.io/CoinBlockerLists/list_optional.txt |  
  | https://raw.githubusercontent.com/w13d/adblockListABP-PiHole/master/Spotify.txt |  
  | https://smokingwheels.github.io/Pi-hole/allhosts |  
  | https://justdomains.github.io/blocklists/lists/easylist-justdomains.txt |  
  | https://justdomains.github.io/blocklists/lists/easyprivacy-justdomains.txt |  
  | https://justdomains.github.io/blocklists/lists/adguarddns-justdomains.txt |  
  | https://justdomains.github.io/blocklists/lists/nocoin-justdomains.txt |  
  | https://dblmobile.oisd.nl/?.txt |  
  | https://hostsmobile.oisd.nl/?.txt |  
  | https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/list.txt |  
  | https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/porn.txt |  
  | https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/adblock.txt |  
  | https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/hosts.txt |  
  | https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt |  
  | https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/hosts.txt |  
  | ttps://raw.githubusercontent.com/gregbakerstl/pihole_block_list/master/gregbakerstl_block_list.txt |  
  | https://hosts-file.net/fsa.txt |  
  | https://hosts-file.net/hjk.txt |  
  | https://phishing.army/download/phishing_army_blocklist.txt

**Comment by GokulG07** [comment]
NO luck as of now. Identifying wildcard conflicts with gravity is getting Killed after 30+min, Tried multiple times, not the latest version(Define regexps chunk size in variable) will try later as my ISP is down now. Attaching all the host I'm using 125 of them hope it helps.
[Black List.txt](https://github.com/mmotti/pihole-gravity-optimise/files/3997662/Black.List.txt)

**Comment by mmotti** [comment]
Hmm.. This is really odd. I don't think the hardware, or more specifically,
memory, is much different across the rpi 2 and 3 either.

I'll try and see if I can replicate this using your blocklists as I was
probably using ~5 in total

**Comment by mmotti** [comment]
OK - So I tried in a VM with 1GB RAM instead of 2GB and it took a little time to complete; 10 minutes or so.

I have found a way, at least on my system, to utilise `grep` still which is highly optimised for this purpose and should perform better on low performance devices with little RAM.

Would you like to give it a try?

**Comment by GokulG07** [comment]
Yes, I can give it a try.

**Comment by mmotti** [comment]
It will still take a little time being that there at over 4M domains but
grep would definitely be the tool to use for this purpose. Fingers crossed

**Comment by GokulG07** [comment]
Wow, it worked...too quick to be true. Great job Motti.

```
[i] Root user detected
[i] Pi-hole path exists
[i] Updating gravity (this may take a little time)
[i] Legacy lists detected
[i] Fetching domains
[i] --> 4368228 domains found
[i] Scanning /etc/dnsmasq.d for wildcards
[i] --> 35539 wildcards found
[i] Identifying wildcard conflicts with gravity
[i] --> 133753 conflicts found
[i] Fetching regexps
[i] --> 16 regexps found
[i] Checking for gravity matches
[i] --> 48947 matches found in gravity
[i] Outputting updated gravity.list
[i] --> 4149990 domains remain in gravity.list
[i] Restarting Pi-hole
```

**Comment by mmotti** [comment]
Yay :-) excellent news!

Did the old shell version ever work for you or did you always get an
allocate error with it?

>

**Comment by GokulG07** [comment]
Yeah always got that allocate error... That's why this Issue thread was opened remember?

**Comment by mmotti** [comment]
Yes - I wasn't sure if it was an intermittent issue or not :-) hopefully
this can be closed off now

**Comment by GokulG07** [comment]
Let me know if you need any help from my side, Just ping.
and Any future plan for the pihole?

**Comment by mmotti** [comment]
Will do :-)

No plans on my end yet - I'm mainly tinkering with stuff for my own amusement. I use AdGuard Home more these days

**Comment by GokulG07** [comment]
Ooh i see. How is AdGuard Home compared to Pihole? Should i give it a try? As I'm using my rpi2 only for blocking ads only nothing else. 
 
  On Wed, 25 Dec 2019 at 5:28 AM, mmotti<notifications@github.com> wrote:   
Will do :-)

No plans on my end yet - I'm mainly tinkering with stuff for my own amusement. I use AdGuard Home more these days

**Comment by mmotti** [comment]
It's a lot more polished and just 'works`. It's a single executable too for
everything; web server, dns filter etc. No flaky install script or shell
scripts to run.

It supports wildcard blocking so no need to use dnsmasq files.

You can also directly add regex files in the way way as host files,
providing the regexps are in the following format: `/regexp/`

Same for whitelist files if you add them in the right format.

I love it

**Comment by GokulG07** [comment]
Ok, I'll give it a try. Thank You
