### ISSUE TITLE
Grep bug(?) ‘Invalid range end’

### ISSUE THREAD

**Issue by willtwilson** [mmotti/pihole-gravity-optimise#5]
Having this issue on this script and also pihole-filter-lists. When running the script manually I get the below error:

> grep: /dev/fd/63:19: Invalid range end

This happens on both of my Pihole pis, which are running DietPi. One is a Pi4, one is slightly older, probably a 3B. 

>   Pi-hole version is v4.3.2 (Latest: v4.3.2)
>   AdminLTE version is v4.3.2 (Latest: v4.3.2)
>   FTL version is v4.3.1 (Latest: v4.3.1)

Google suggests to me it might be a bug with how grep handles hyphens. 

Thanks!

**Comment by mmotti** [comment]
It's been a while since I have looked at these scripts as I haven't used pihole in a while but I have come across this kind of issue before, specifically using `[a-z0-9-_.]` - I don't believe I used this kind of regexp in this case, but my suspicion is that there may be a domain that ends with a hyphen which is causing this error.

Please could you share the blocklists that you are using?

**Comment by willtwilson** [comment]
> Please could you share the blocklists that you are using?

Sure, there's quite a few of them, aggregating to a block count of about 1.5m

`https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts	
https://mirror1.malwaredomains.com/files/justdomains	
http://sysctl.org/cameleon/hosts	
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist	
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt	
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt	
https://hosts-file.net/ad_servers.txt	
https://hosts-file.net/grm.txt	
https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts	
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts	
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts	
https://v.firebog.net/hosts/static/w3kbl.txt	
https://adaway.org/hosts.txt	
https://v.firebog.net/hosts/AdguardDNS.txt	
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt	
https://v.firebog.net/hosts/Easylist.txt	
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts;showintro=0	
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts	
https://www.squidblacklist.org/downloads/dg-ads.acl	
https://v.firebog.net/hosts/Easyprivacy.txt	
https://v.firebog.net/hosts/Prigent-Ads.txt	
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt	
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts	
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt	
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
https://hosts-file.net/exp.txt	
https://hosts-file.net/emd.txt	
https://hosts-file.net/psh.txt	
https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt	
https://www.malwaredomainlist.com/hostslist/hosts.txt	
https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt	
https://v.firebog.net/hosts/Prigent-Malware.txt	
https://v.firebog.net/hosts/Prigent-Phishing.txt	
https://phishing.army/download/phishing_army_blocklist_extended.txt	
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt	
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt	
https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt	
https://ransomwaretracker.abuse.ch/downloads/LY_C2_DOMBL.txt	
https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt	
https://ransomwaretracker.abuse.ch/downloads/TL_C2_DOMBL.txt	
https://v.firebog.net/hosts/Shalla-mal.txt	
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts	
https://www.squidblacklist.org/downloads/dg-malicious.acl	
https://zerodot1.gitlab.io/CoinBlockerLists/hosts	
Https://dbl.oisd.nl`

**Comment by tempissue** [comment]
slightly off topic @mmotti, but what are you using instead?

**Comment by willtwilson** [comment]
I’ve seen mentions quite a few times elsewhere of people using a pfsense module to do network adblocking.

**Comment by mmotti** [comment]
Thanks @willtwilson - This will help me test in a dietpi vm.

@tempissue I personally prefer AdGuard Home: https://github.com/AdguardTeam/AdGuardHome

It's a single executable that you install as a service as it does the dns filter, web server, everything. Just feels a lot more polished overall. Oh, and you can use filter list format e.g. `||test.com^` to wildcard block stuff! :-)

**Comment by mmotti** [comment]
OK - Running DietPi in VMware Workstation with 1GB RAM, 8GB storage and 1 processor, it seems to work OK on my end with the provided blocklists.

1. `pihole -g` --> [i] Number of unique domains trapped in the Event Horizon: **1508546**
2. `fetchFilterlists.sh`:
```
dietpi@DietPi:~$ fetchFilterLists.sh
[i] Selected filter sources: adguarddns,easylist,easyprivacy,nocoin
[i] Fetching domains
[i] Parsing existing wildcard config (DNSMASQ)
[i] Cleaning domains
[i] Removing regex.list conflicts
[i] Checking whitelist conflicts
[i] Determining output format
[i] Constructing output
[i] 35864 domains added to /etc/dnsmasq.d/filter_lists.conf
[i] Restarting FTL
[i] Done
```
3. `gravityoptimise.sh`
```
dietpi@DietPi:~$ gravityOptimise.sh
[i] Updating gravity
[i] Parsing existing wildcard config (DNSMASQ)
[i] Removing wildcard matches from gravity
[i] Updating gravity database
[i] Removing temp files
[i] Refreshing Pihole
[i] 105228 domains were removed from gravity
[i] 1403318 domains remain in gravity
```

Theoretically we should be using the same hosts etc. At exactly which point in the script does it break? What do you see as the 'status update' just before the error?

Edit: Ah, wait a minute. Is it as it's trying to run the regex removals?
