### ISSUE TITLE
Unmatched ( or \(

### ISSUE THREAD

**Issue by jostyee** [mmotti/pihole-gravity-optimise#7]
Hi,

I met an error when running this script:

```
$ gravityOptimise.sh
[i] Updating gravity
[i] Parsing existing wildcard config (DNSMASQ)
[i] Removing regex matches from gravity
grep: /dev/fd/63:31: Unmatched ( or \(
[i] 0 domains remain after regex removals
```

on debian
Linux foo.com 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux

anyway to debug? Thanks in advance.

**Comment by mmotti** [comment]
This would suggest to me that one or more of your regexps are invalid.

Please could you confirm the regular expressions that you are using?

**Comment by jostyee** [comment]
Thanks, I missed a `)` in one rule, it works now.

```
[i] Updating gravity
[i] Parsing existing wildcard config (DNSMASQ)
[i] Removing regex matches from gravity
[i] Updating gravity database
[i] Removing temp files
[i] Refreshing Pihole
[i] 28795 domains were removed from gravity
[i] 571855 domains remain in gravity
```
